name: StreetSpot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.7.2
  awesome_bottom_bar: ^1.2.4
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  gif: ^2.3.0
  toastification: ^3.0.1
  loading_animation_widget: ^1.3.0
  hugeicons: ^0.0.11
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  mask_text_input_formatter: ^2.9.0
  flutter_rating_bar: ^4.0.1
  pinput: ^5.0.1
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.39
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Launcher icon support
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/loginlogo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: PlusJakartaSansBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
    - family: PlusJakartaSansExtraBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
    - family: PlusJakartaSansExtraLight
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
    - family: PlusJakartaSansLight
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
    - family: PlusJakartaSansMedium
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
    - family: PlusJakartaSansRegular
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
    - family: PlusJakartaSansSemiBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
    - family: PlusJakartaSansVariableFont
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf